# SF311 requests

Use the [Week 4 project guide](README.md) and [data reference](data/README.md). Copy the entire lesson folder to a practice folder outside the course checkout so notebook, scripts, and `data/` stay together. Open that folder in VS Code and select the course `.venv` kernel.

The first cell prints the working directory. It should be your practice folder: the next cell expects `data/sf311_requests.csv`, and later cells import `case_summary.py` from there. If either is missing, check the folder before editing paths.

Run cells in order and compare the tables with the supplied report. **Size** counts rows, **count** counts non-missing durations, and **median** is the middle observed duration. `dropna=False` keeps requests whose district is unknown. Check that the sum of grouped request counts equals `len(requests)`.

After editing `case_summary.py`, save it and restart the kernel before rerunning this notebook so Python imports the new version. The final blank cell is available for your own checks.

In [2]:
!pwd

/Users/tomvannuenen/Library/CloudStorage/Dropbox/GitHub/DEV/compss-211a/lessons/week04_reproducible-analyses

In [3]:
import pandas as pd

requests = pd.read_csv("data/sf311_requests.csv")

In [8]:
requests.columns

Index(['request_id', 'opened_at', 'closed_at', 'status', 'category', 'channel',
       'district', 'hours_to_close', 'duration_note'],
      dtype='object')

In [17]:
original_report = requests.groupby("district", dropna=False)["hours_to_close"].agg(
    requests="size",
    with_time="count",
    median_hours="median")

original_report

          requests  with_time  median_hours
district
1.0           1064       1010      5.467361
2.0           1347       1236      5.497778
3.0           2357       2158     14.136389
4.0            697        671      3.611944
5.0           1926       1816     12.096389
6.0           2139       1995     13.803333
7.0            781        721     15.328611
8.0           1793       1689      9.395833
9.0           2536       2366      6.136944
10.0          1232       1139     13.887500
11.0           894        842      5.261528
NaN            110        100     27.614861

In [10]:
len(requests)

16876

In [12]:
original_report["requests"].sum()

np.int64(16766)

In [15]:
requests["district"].isna().sum()

np.int64(110)

In [16]:
requests.loc[requests["district"].isna()]

,request_id,opened_at,closed_at,status,category,channel,district,hours_to_close,duration_note
229,101004551809,2026-08-03T07:25:50.000,2026-09-16T18:21:06.000,Closed,General Request,NaN,NaN,1066.921111,Recorded
819,101004553128,2026-08-03T09:42:28.000,2026-08-12T11:00:38.000,Closed,General Request,Phone,NaN,217.302778,Recorded
1131,101004554107,2026-08-03T11:21:56.000,2026-08-03T12:53:52.000,Closed,RPD General,Mobile,NaN,1.532222,Recorded
1451,101004555145,2026-08-03T13:19:45.000,2026-08-10T01:00:00.000,Closed,General Request,Phone,NaN,155.670833,Recorded
1495,101004555328,2026-08-03T13:41:25.000,2026-08-03T14:29:03.000,Closed,311 Complaints,Phone,NaN,0.793889,Recorded
...,...,...,...,...,...,...,...,...,...
15717,101004591985,2026-08-09T12:39:09.000,2026-08-10T11:10:16.000,Closed,Taxi Complaint,Phone,NaN,22.518611,Recorded
15792,101004592158,2026-08-09T13:12:25.000,2026-08-10T14:20:26.000,Closed,Muni Employee Feedback,Phone,NaN,25.133611,Recorded
16306,101004593281,2026-08-09T16:59:45.000,2026-08-27T14:04:10.000,Closed,Muni Service Feedback,NaN,NaN,429.073611,Recorded
16512,101004593729,2026-08-09T18:23:31.000,NaN,Open,General Request,Phone,NaN,NaN,No closure recorded
16729,101004594191,2026-08-09T20:27:01.000,2026-08-10T08:14:21.000,Closed,Muni Employee Feedback,Phone,NaN,11.788889,Recorded

In [18]:
pd.__file__

'/Users/tomvannuenen/Library/CloudStorage/Dropbox/GitHub/DEV/compss-211a/.venv/lib/python3.13/site-packages/pandas/__init__.py'

In [19]:
import case_summary

In [20]:
case_summary.summarize_requests(requests, group_by="district")

    district  requests  with_time  median_hours
0        1.0      1064       1010          5.47
1        2.0      1347       1236          5.50
2        3.0      2357       2158         14.14
3        4.0       697        671          3.61
4        5.0      1926       1816         12.10
5        6.0      2139       1995         13.80
6        7.0       781        721         15.33
7        8.0      1793       1689          9.40
8        9.0      2536       2366          6.14
9       10.0      1232       1139         13.89
10      11.0       894        842          5.26
11       NaN       110        100         27.61

In [24]:
selected = requests.loc[requests["category"] == "Street and Sidewalk Cleaning"]
len(selected)

6261

In [25]:
draft_report = selected.groupby("district", dropna=False)["hours_to_close"].agg(
    requests="size",
    with_time="count",
    median_hours="median")

draft_report

          requests  with_time  median_hours
district
1.0            280        279      4.919167
2.0            442        438      3.967222
3.0            854        842     11.961667
4.0            173        172      3.243333
5.0            831        826      8.580278
6.0            869        860     13.747222
7.0            205        204     14.852083
8.0            560        558      3.611250
9.0           1152       1142      3.817500
10.0           553        535     14.206389
11.0           342        340      2.632361

In [ ]:
draft_report["pct_with_time"] = draft_report["with_time"] / draft_report["requests"] * 100

In [27]:
draft_report

          requests  with_time  median_hours  pct_with_time
district
1.0            280        279      4.919167      99.642857
2.0            442        438      3.967222      99.095023
3.0            854        842     11.961667      98.594848
4.0            173        172      3.243333      99.421965
5.0            831        826      8.580278      99.398315
6.0            869        860     13.747222      98.964327
7.0            205        204     14.852083      99.512195
8.0            560        558      3.611250      99.642857
9.0           1152       1142      3.817500      99.131944
10.0           553        535     14.206389      96.745027
11.0           342        340      2.632361      99.415205