# September 11 Support Session: Python Repair

**COMPSS 211A | Fall 2026 | Student copy**

**Friday, September 11, 2026**

Today we will learn how to read a Python error, find a misspelled column name, and make a clear choice about a missing value. The records are made up for practice.

## Before we start

Click a code cell and press **Shift + Enter**. Work from top to bottom. The setup is grouped in one cell; each lesson code cell has one line.

This is a no-AI practice session. Ask your neighbor or the instructor when you get stuck.

## Setup check

Run this cell once. It loads the packages, creates our made-up practice table, checks the versions, and shows the Python and folder this notebook is using.

The local course setup uses Python **3.13**, pandas **2.2.3**, and NumPy **2.1.3**.

In [1]:
import platform
import sys
from pathlib import Path
import pandas as pd
import numpy as np

tiny = pd.DataFrame({"place": ["Doe", "Moffitt", "D-Lab", "Main Stacks", "Ethnic Studies"], "seats": [40, None, 18, 65, 12], "visitors": [120, 95, None, 150, 40]})

print("Python version:", platform.python_version())
print("Python 3.13:", platform.python_version().startswith("3.13."))
print("pandas version:", pd.__version__)
print("pandas matches 2.2.3:", pd.__version__ == "2.2.3")
print("NumPy version:", np.__version__)
print("NumPy matches 2.1.3:", np.__version__ == "2.1.3")
print("Python location:", sys.executable)
print("Working folder:", Path.cwd())

Python version: 3.13.9
Python 3.13: True
pandas version: 3.0.3
pandas matches 2.2.3: False
NumPy version: 2.4.6
NumPy matches 2.1.3: False
Python location: /opt/anaconda3/bin/python
Working folder: /Users/mac/Documents/GitHub/compss-211a/lab

If you see an import error or a version check says `False`, show the result to the instructor or GSI. Colab versions may differ, so ask before changing packages.

## 1. Look at the table

Run each line, then tell your neighbor what the result shows.

Show all five made-up records.

In [2]:
tiny

            place  seats  visitors
0             Doe   40.0     120.0
1         Moffitt    NaN      95.0
2           D-Lab   18.0       NaN
3     Main Stacks   65.0     150.0
4  Ethnic Studies   12.0      40.0

Show the number of rows and columns.

In [3]:
tiny.shape

(5, 3)

Show the column names. We will use this list when we repair an error.

In [4]:
tiny.columns

Index(['place', 'seats', 'visitors'], dtype='str')

## 2. Read an error and find the problem

Imagine that we tried to select a column named `seat` and Python showed this message:

```text
KeyError: 'seat'
```

Start with the **last line**. `KeyError: 'seat'` means Python could not find the label `seat`. Save that label so we can check it.

In [5]:
wrong_column = "seat"

Ask whether that label is in the table’s column names. Predict `True` or `False` before running it.

In [6]:
wrong_column in tiny.columns

False

Compare the requested label with the available names. The table has `seats`, with an **s**.

In [7]:
correct_column = "seats"

Select the repaired column and save it as `seat_counts`.

In [8]:
seat_counts = tiny[correct_column]

Show the values in the repaired column.

In [9]:
seat_counts

0    40.0
1     NaN
2    18.0
3    65.0
4    12.0
Name: seats, dtype: float64

## 3. Notice the missing value

`NaN` means a value is missing. It does not mean zero. Ask which place has a missing seat count.

In [10]:
seat_counts.isna()

0    False
1     True
2    False
3    False
4    False
Name: seats, dtype: bool

Count how many seat values are missing. In Python, `True` counts as 1.

In [11]:
seat_counts.isna().sum()

np.int64(1)

Keep only the seat counts that are present.

In [12]:
observed_seats = seat_counts.dropna()

Show the observed values.

In [13]:
observed_seats

0    40.0
2    18.0
3    65.0
4    12.0
Name: seats, dtype: float64

Find the average of the observed seat counts.

In [14]:
observed_average = observed_seats.mean()

Show the observed-value average.

In [15]:
observed_average

np.float64(33.75)

## 4. Compare a different missing-value choice

Here we temporarily replace the missing seat count with zero. This asks a different question because an unknown count becomes a known zero.

In [16]:
zero_filled_seats = seat_counts.fillna(0)

Show the values after filling the missing value.

In [17]:
zero_filled_seats

0    40.0
1     0.0
2    18.0
3    65.0
4    12.0
Name: seats, dtype: float64

Find the average after replacing the missing value with zero.

In [18]:
zero_filled_average = zero_filled_seats.mean()

Show the new average. Is it the same as the observed-value average?

In [19]:
zero_filled_average

np.float64(27.0)

## 5. Choose rows after the repair

First, remove rows where the seat count is missing. This gives us a table with observed seat counts.

In [20]:
known_seats = tiny.dropna(subset=["seats"])

Make a rule that asks which observed counts are at least 20.

In [21]:
has_20_seats = known_seats["seats"] >= 20

Use the rule to keep those rows.

In [22]:
larger_places = known_seats[has_20_seats]

Show the result.

In [23]:
larger_places

         place  seats  visitors
0          Doe   40.0     120.0
3  Main Stacks   65.0     150.0

## 6. Make and use a function

A function gives a short name to a reusable action. `count` is the input. The `return` line sends a result back.

In [24]:
def seat_message(count):
    return f"{count} seats available"

Call the function with the number 18. The value inside the parentheses becomes `count`.

In [25]:
seat_message(18)

'18 seats available'

Call the same function with our observed-value average.

In [26]:
seat_message(observed_average)

'33.75 seats available'

## Work with your neighbor

Spend about **10 minutes** on these tasks. One person types while the other explains each line. **Swap roles after each task.** Use one line per blank code cell.

### Task 1: Repair another column name

Someone wrote `visitor`, but the table uses a different label. Save the incorrect name, check whether it exists, save the correct name, select that column, and show its values.

In [27]:
wrong_visitor = "visitor"

In [46]:
wrong_visitor in tiny.columes

AttributeError: 'DataFrame' object has no attribute 'columes'

In [30]:
correct_visitor = "visitors"

In [31]:
visitor_counts = tiny[correct_visitor]

In [32]:
visitor_counts

0    120.0
1     95.0
2      NaN
3    150.0
4     40.0
Name: visitors, dtype: float64

### Task 2: Work with the observed visitor counts

Remove the missing visitor count, show the remaining values, and find their average. Tell your neighbor how many values the average uses.

In [33]:
observed_visitors = visitor_counts.dropna()

In [34]:
observed_visitors

0    120.0
1     95.0
3    150.0
4     40.0
Name: visitors, dtype: float64

In [36]:
observed_visitors.mean()

np.float64(101.25)

### Task 3: Choose smaller places

Starting from `known_seats`, make a rule for places with fewer than 20 seats. Use the rule to select the rows, then show the result.

In [38]:
under_20seats = known_seats["seats"] < 20

In [39]:
smaller_places = known_seats[under_20seats]

In [40]:
smaller_places

            place  seats  visitors
2           D-Lab   18.0       NaN
4  Ethnic Studies   12.0      40.0

### Task 4: Adapt a function

Use the example above to define a function named `visitor_message`. Give it an input named `count` and return a message ending in `visitors`. Then call it with `observed_visitors.mean()`.

In [42]:
def visitor_message(count):
    return f"{count} visitors"

In [45]:
visitor_message(observed_visitors.mean())

'101.25 visitors'

**Before moving on:** Pick one repair and explain how the error message and column list helped you fix it.

## Your notes

Write one thing you can now do and one question you still have.

I can now write function, My question is

## Exit

The last 10 minutes are reserved for Quiz 2. Save your notebook before the quiz.